code/agent/Infrastructure.py, code/agent/Telemetry.py, code/agent/common/nuvlabox.py, code/app.py, code/requirements.txt, docker-compose.localhost.yml, docker-compose.onpremise.yml
Initial implementation of recommission action.
=> recommission

code/agent/Telemetry.py
Simplify the load average calculation by reading `/proc/loadavg` directly.  (The previous implementation with `top` doesn't provide consistent output on different devices.) Catch exceptions when converting to float to avoid having the container crash.
=> simplify load avg

code/agent/Telemetry.py
=> Expand telemetry

Dockerfile, code/agent/Telemetry.py, code/agent/common/NuvlaBoxCommon.py, docker-compose.yml
=> Gpio telemetry

code/agent/Telemetry.py, code/agent/common/NuvlaBoxCommon.py
fixes https://github.com/nuvlabox/agent/issues/34
=> Report version

code/agent/Telemetry.py
fixes https://github.com/nuvlabox/agent/issues/39
=> add get for docker plugins

code/agent/Telemetry.py, code/agent/common/NuvlaBoxCommon.py
fixes https://github.com/nuvlabox/agent/issues/33
=> Ip based geolocation

code/agent/Telemetry.py
fixes https://github.com/nuvlabox/agent/issues/45
=> Nb status topic

code/agent/AgentApi.py
fixes https://github.com/nuvlabox/peripheral-manager-network/issues/4
=> Per check post

code/app.py
@mebster once the rationale has also been improved on server-side, please use this agent branch to test the flapping state.
fixes https://github.com/nuvlabox/agent/issues/64
=> add dynamic wait for next cycle based on time elapsed

code/agent/Telemetry.py, code/app.py
fixes https://github.com/nuvlabox/agent/issues/81
=> separate telemetry from heartbeat

code/agent/Infrastructure.py, code/agent/common/NuvlaBoxCommon.py, code/app.py
fixes https://github.com/nuvlabox/agent/issues/90
tested with kubeadm and k0s installations
=> bring back k8s discovery fn

.gitignore, code/agent/common/NuvlaBoxCommon.py, code/tests/test_nuvlabox_common.py
fixes https://github.com/nuvlabox/deployment/issues/69
┆Issue is synchronized with this [Trello card](https://trello.com/c/mT5BwdtB) by [Unito](https://www.unito.io)
=> check if provided UUID is different from old one - avoid overwriting

code/agent/Telemetry.py, code/agent/common/NuvlaBoxCommon.py, code/tests/test_nuvlabox_common_docker_client.py, code/tests/utils/fake.py
=> Nuvlabox log

code/agent/common/NuvlaBoxCommon.py, code/tests/test_nuvlabox_common_docker_client.py
fixes https://github.com/nuvlabox/agent/issues/99
=> only take the config files from the last update

code/app.py
closes https://github.com/nuvlabox/deployment/issues/71
=> make logging level configurable

.github/workflows/main.yml
Build on push to master, PRs, and manually triggered
Related to #110 
The result is a single build
=> build on push to master, PRs, and manually triggered

.github/workflows/validation.yml
In  order to test the correct functionality of the workflow I need it to be merged into main so it triggers after the Build workflow in pull requests
=> Added validation CI workflow

code/agent/common/NuvlaEdgeCommon.py, code/agent/common/util.py, code/agent/infrastructure.py, code/agent_main.py, code/tests/test_infrastructure.py
=> Recommission VPN if OpenVPN config is not available and do nothing is VPN client container doesn't exist.

.github/workflows/validation.yml, code/agent/common/util.py, code/agent/infrastructure.py, code/agent/orchestrator/__init__.py, code/agent/orchestrator/docker.py, code/tests/test_nuvlaedge_common_docker_client.py
=> Added support for isolation using hardcoded container names

CHANGELOG.md, code/agent/common/nuvlaedge_common.py, code/agent/common/util.py, code/agent/infrastructure.py, code/agent/orchestrator/docker.py, code/tests/orchestrator/test_docker_client.py, code/tests/test_infrastructure.py
Closes nuvlaedge/deployment#83
=> Added support for COMPUTE API port auto assignment

code/agent/common/nuvlaedge_common.py, code/tests/test_nuvlaedge_common.py
=> Vpn automatic interface name

CHANGELOG.md, code/agent/infrastructure.py, code/agent/monitor/components/container_stats.py, code/agent/monitor/data/orchestrator_data.py, code/agent/orchestrator/__init__.py, code/tests/monitor/components/test_container_stats.py, code/tests/orchestrator/test_kubernetes_client.py, code/tests/test_infrastructure.py
=> Removed COE labels from commissioning process

code/agent/common/nuvlaedge_common.py, code/agent/common/util.py, code/agent/infrastructure.py, code/agent/monitor/__init__.py, code/agent/monitor/components/network.py, code/agent/monitor/components/nuvlaedge_info.py, code/agent/orchestrator/__init__.py, code/agent/orchestrator/docker.py, code/agent/orchestrator/kubernetes.py, code/agent/telemetry.py, code/tests/monitor/components/test_network.py, code/tests/orchestrator/test_docker_client.py, code/tests/orchestrator/test_kubernetes_client.py, code/tests/test_infrastructure.py
This PR 
- fixes the collection of network interfaces when COE is K8s
- refactored the creation and launching of pods
- launching of Nuvla jobs uses K8s jobs instead of pods
Fixes #143
=> k8s fixes and refactors
